---
title: "p8105_hw6_kx2173"
author: "Ke Xu"
date: "12/4/2021"
output: html_document
---

```{r}
library(tidyverse)
library(modelr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Problem 1

Load and clean the data for regression analysis.
```{r}
birthweight_df = read.csv("birthweight_data/birthweight.csv") %>% 
  janitor::clean_names()

# Check missing value
sum(is.na(birthweight_df))

birthweight_df = birthweight_df %>% 
  mutate(
    babysex = factor(babysex, ordered = FALSE),
    frace = factor(frace, ordered = FALSE),
    malform = factor(malform, ordered = FALSE),
    mrace = factor(mrace, ordered = FALSE)
  )
```

Propose a regression model for birthweight.
```{r}
model_1 = lm(bwt ~ ppbmi + delwt, data = birthweight_df) 

model_1 %>% broom::tidy()

plot = birthweight_df %>% 
  add_residuals(model_1) %>% 
  add_predictions(model_1) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = 0, intercept = 0, color = "red") +
  labs(
    title = "Residuals vs Fitted value Plot",
    x = "Fitted value",
    y = "Residuals"
  ) +
  theme(plot.title = element_text(hjust = 0.5))

```

















